### ISSUE TITLE
Enable SDCcc to detect Encoding-Problems

### ISSUE THREAD

**Issue by ldeichmann** [Draegerwerk/SDCcc#2]
Currently, SDCcc assumes that the encoding declared by the Device under Test in the HTTP Header or XML declaration is correct and decodes the messages accordingly.

This process using the String(byteArray, charset)-Constructor, which silently replaces unmappable characters by a charset-specific "Unmapped"-character. Hence,

- SDCcc does not notice when the encoding is set incorrectly, and
- in the worst case, the unmapped-Characters resulting from an incorrectly set encoding might even cause FalseNegatives in our Invariant Tests.
- Since the Message Content is partly lost (replaced by Unmapped-Characters), this additionally hinders Confirmability of SDCcc Test Results.

It would hence be better to use the CharsetDecoder class instead of the String-Constructor mentioned above, as it allows detecting unmappable character during the decoding process. It would hence become possible to invalidate the Test run when encountering unmappable Characters which indicate an incorrectly-set encoding and provide the user with an informative reason.

Hint: start from the TODO with this Ticket's Number in MessageStorage.

**Comment by ben-Draeger** [comment]
Solved by [PR#108](https://github.com/Draegerwerk/SDCcc/pull/108). Thus closing this issue.
