### ISSUE TITLE
Charset determination from messages

### ISSUE THREAD

**Issue by belagertem** [Draegerwerk/SDCcc#48]
Due to compatibility issues, message encoding determination has been turned off and messages are assumed to be encoded in UTF-8.

**Comment by ben-Draeger** [comment]
[PR#90](https://github.com/Draegerwerk/SDCcc/pull/90) introduces a Configuration Option for ths purpose. It also re-enables using the charset specified in the message to decode it.

When the PR is merged, this issue is hence resolved.

**Comment by ben-Draeger** [comment]
PR #90 is merged, thus closing this issue.
